### ISSUE TITLE
adding menus

### ISSUE THREAD

**Issue by aoloe** [nitramr/indigoDock#12]
i'm working on menus for indigo... they will be read from a json file

**Comment by nitramr** [comment]
In my UI concept I have planned a customizable ToolBar (shortcut bar) with buttons they do the same like menu entries. Would it be possible to use your code to fill these bar too?

More details about the concept here:
https://docs.google.com/presentation/d/1M6R4ggFbgU1EXbWiL8hwppyQJhsNnUlw7_7rOA3Im1Q/edit#slide=id.gcb561e9b3_0_9

**Comment by aoloe** [comment]
i think that it could be used for prototyping it, yes.
and for finding which items can be added to the toolbar!

but, i understand your goal correctly, a small customizable toolbar sould be stored in the scribus config files.

**Comment by nitramr** [comment]
Ok, if it so simple it can be stored in the config file.

**Comment by aoloe** [comment]
ok, i have the code to add the navigation from a json file...
i will make a pull request on friday...
the next step will be to understand how to bind it with actions so that we can also manage the keyboad shortcuts and the toolbar with it...
