### ISSUE TITLE
OSX after f8bb077

### ISSUE THREAD

**Issue by luzpaz** [nitramr/indigoDock#14]
after f8bb077eb3fc0f4863181f300d3e164717c829ac was committed, MacOSX UI looks like this:

![indigodock](https://cloud.githubusercontent.com/assets/4140247/11260263/032ae638-8e2f-11e5-946a-2b780f05b0ee.gif)

**Comment by nitramr** [comment]
Hey, its Not really an issue. The Panels with arrow Down icon have invalid content to test the behaviour. In commitments ago the App would be crashed if there no dropzone object. Now its fixed.
