### ISSUE TITLE
abusing your effort...

### ISSUE THREAD

**Issue by aoloe** [nitramr/indigoDock#16]
hey

would you mind if i abuse of your project for testing other things like:
- the python scripter
- a d-bus interface (http://doc.qt.io/qt-5/qtdbus-index.html)

the idea is to create technology previews to test/show how it would work...

**Comment by nitramr** [comment]
I'm not sure if it will grow up in a wrong direction. The initial idea of these project is to work on new UI elements. Perhaps it makes more sense to create a new project for technology previews only. If it is UI related let's integrate the stuff. For technical stuff only I think a separate project is the better way. What do you think about?

**Comment by aoloe** [comment]
well, in my eyes, what you are doing is a technology preview for the UI :-)

i just thought that it could have been practical to have a repository where several people work on new ideas for scribus and can help each when questions arise...

but we can for sure have one (ore more) testbed für the UI and the same for other ideas!

**Comment by nitramr** [comment]
You mean like a test lab for new features which will (if confirmed) implement in Scribus? Ok, then we have to re-think this bucket for several new features. Let's give it a try! If it run in to a wrong direction we can split it afterwards.

**Comment by aoloe** [comment]
well the idea is not to fully implement the feature (like you won't be implementing the formatting of the frames!), just implement it to the point that it can be shown to the team to convince them that it can also work for scribus :-)

i have now created "a new general indigo": https://github.com/impagina/indigo

... now that it exists, i think that i will at least put in there a study on a clean code structure... and other structural things... and we can add them in here if it shows to be useful!

anyway, i think that it would be really good to have a place where people can test new features without having to mess with all the "scribus cruft"...
and the overall structure is kept simple enough, it will be easier for new contributors to extend it rather than start the project from scratch as you are doing, now! (and you're really doing a great job!)

**Comment by aoloe** [comment]
p.s.: we don't have to overthink it... let's see if things happen and then find a solution :-)
