### ISSUE TITLE
widgets remain in the forefront when switching away from indigoDock Tester

### ISSUE THREAD

**Issue by luzpaz** [nitramr/indigoDock#28]
OSX 10.10.5 Qt5.6 indigoDock 6249eedf56418ee1df49c1f040fc33e64de0abbd
See screenshot (I did an `alt+tab` and widgets remained in the forefront)

![up-front-widgets](https://cloud.githubusercontent.com/assets/4140247/14065295/a286eab8-f3e9-11e5-829d-bb298611f3f3.png)

**Comment by nitramr** [comment]
I found the reason. It was because Qt::WindowStaysOnTopHint was setted as WindowFlag on panels. But it's not needed if the panels has a parent.

**Comment by luzpaz** [comment]
FYI Issue still present in 7cc78803c74878172da6b433bfb4eee39ba06dab

**Comment by nitramr** [comment]
Can you check again? Should be fixed in 0b71b934605ee596864cc0b69fb398606bed62f2

**Comment by luzpaz** [comment]
Fixed in 0b71b93 !
Thanks @nitramr 
Closing
