### ISSUE TITLE
panel placement on GNOME

### ISSUE THREAD

**Issue by corebots** [nitramr/indigoDock#30]
thank you for the update. running latest indigoDock in Qt Creator on Fedora 23 results in a panel in top left corner unable to move or click 'x':
![screenshot from 2016-05-15 22-50-44](https://cloud.githubusercontent.com/assets/12252430/15276730/cda93e70-1af0-11e6-9c96-f01976cfd658.png)

**Comment by nitramr** [comment]
Hi Corebot, I can move and close these tool window on my Ubuntu 16.04. Can you drag out and close other panels? I see some errors in your console, can you put the output here? Furthermore the last letter in panel caption is cutted off. I think I have to fix something. Thanks for testing, that will make it more stable.

greets,
Martin.

PS: I guess it is why the panel cover the section of top bar. Maybe I have to move the inital position of these floating panel a little bit more to the bottom.

**Comment by corebots** [comment]
Well it might be different in Ubuntu Unity, i can't test. But the top panel of GNOME-Shell seems to be blocking click-input on its area even if the indigoDock panel it being drawn on top of it. The two controls react, i can enter text and change the angle, but the top part with the 'x' button is un-clickable. 

I can not drag it out. Furthermore, when I drag out another panel from the dock and place it next to the stuck panel it gets stuck too :/ 

The labels are cut on their last letter yes. Might be worth mentioning that the slider remains there until only one panel is visible on the dock and the panels are not to bring back once i've closed them - clicking icons on the right bar does nothing. 

Output:
Starting /home/core/Downloads/indigoDock-master/build/TestLayout...
Fontconfig error: "/etc/fonts/conf.d/66-google-noto-sans-brahmi.conf", line 1: no element found
Fontconfig error: "/etc/fonts/conf.d/66-google-noto-sans-brahmi.conf", line 1: no element found
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast

**Comment by luzpaz** [comment]
@corebots what version of Qt Creator are you running ?

**Comment by luzpaz** [comment]
Can't recreate on revision: 7cc78803c74878172da6b433bfb4eee39ba06dab 
OSX 10.10.5 Qt5.6 Qt Creator 4.0

**Comment by corebots** [comment]
hmm. I was running Qt Creator 3.6.1 Based on Qt 5.6.0 (GCC 5.3.1 20151207 (Red Hat 5.3.1-2), 64 bit). But now I've downloaded and installed Qt Creator 4.0.0. The 'about' screen now sais: Based on Qt 5.6.0 (GCC 4.9.1 20140922 (Red Hat 4.9.1-10), 64 bit). I've also cloned latest code from git.

unfortunately, all issues remain the same :(

**Comment by corebots** [comment]
I've now also tested on latest Fedora 24beta which sits on my second hdd. downloaded Qt Creator 4.0.0 Based on Qt 5.6.0 (GCC 6.0.0 20160406 (Red Hat 6.0.0-0.20), 64 bit) and cloned the indigoDock code. I get this when trying to configure it: 

12:50:38: Running steps for project TestLayout...
12:50:38: Starting: "/usr/bin/qmake-qt5" /home/xxxx/Downloads/indigoDock-master/TestLayout.pro -r -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
Project ERROR: Unknown module(s) in QT: designer
12:50:38: The process "/usr/bin/qmake-qt5" exited with code 3.
Error while building/deploying project TestLayout (kit: Desktop)
When executing step "qmake"
12:50:38: Elapsed time: 00:00.

I must let you know I have no experience with qt. Just followed your instructions and these are the results, not sure if this is even helpful - hope I'm not bringing too much confusion in :)

**Comment by nitramr** [comment]
I'm using Qt Creator 3.6.0 - Based on Qt 5.6.0 (GCC 4.9.1 20140922 (Red Hat 4.9.1-10), 64 bit)

**Comment by nitramr** [comment]
So, I changed something in the code. Maybe I found the reason, the window state of the floating panel was setted to 'tooltip' instead of 'tool'. That could be the reason why you couldn't move it. It should be fixed now in 0b71b934605ee596864cc0b69fb398606bed62f2. Can you try again?

**Comment by corebots** [comment]
I can confirm that the panel placement is fixed now ;) the panel appears now below the GNOME top bar and is movable. thank you

**Comment by nitramr** [comment]
Great, than I'll close the issue here.
