### ISSUE TITLE
clicking and dragging down on toolbars/sidebars duplicates last icon

### ISSUE THREAD

**Issue by luzpaz** [nitramr/indigoDock#31]
Running 7cc78803c74878172da6b433bfb4eee39ba06dab on MacOS 10.10.5 
Reproduce:
1. Click and hold down on one of the toolbars
2. Drag the mouse down
Result: see gif

![weird-side-bar-icon-duplication](https://cloud.githubusercontent.com/assets/4140247/15309770/54583f8e-1baf-11e6-8aa6-2459f54e839a.gif)

**Comment by nitramr** [comment]
Should be fixed in a39a9355895687cfdb31f678dce4851e5668c6bd. Please, can you confirm?

**Comment by luzpaz** [comment]
Confirmed fix in a39a935
Thanks @nitramr !
