### ISSUE TITLE
'Save Workspace'; then move toolbar to horizontal position; 'Load Workspace' doesn't return to previous state

### ISSUE THREAD

**Issue by luzpaz** [nitramr/indigoDock#35]
OSX 10.10.5 7cc78803c74878172da6b433bfb4eee39ba06dab
1. Press 'Save Workspace'
2. Move a toolbar in to a horizontal position
3. Press 'Load Workspace' to restore pre-horizontal toolbar state
Result: Horizontal state is now the new saved instance. Previous state is no longer available.

**Comment by nitramr** [comment]
Yes, that's right. Saving of dock states itself are currently not implemented. Only the state of single panels within a dock will be save.

**Comment by luzpaz** [comment]
i see. should I change the ticket name to reflect that or should i close it ?

**Comment by nitramr** [comment]
I will close it because dock state saving is planned for next workspace upgrade.
