### ISSUE TITLE
clicking and dragging toolbars/sidebars duplicates last icon in a different way

### ISSUE THREAD

**Issue by luzpaz** [nitramr/indigoDock#36]
This is slightly different than #31 so I opened a new ticket:
To reproduce:
1. Click and hold on the left toolbar in an empty space (not on a icon)
2. While the mouse button is still depressed  move the mouse upwards towards the icon above it
Result: 
On the left toolbar: the above icon will be a duplicate of the icon that you're moving
On the right toolbar: you'll see the same phenomena as the left toolbar + the first icon at the top of the toolbar disappears.
See gif

![duplicate-icon-case-2](https://cloud.githubusercontent.com/assets/4140247/15382137/6b29a60a-1d4c-11e6-9646-02ec5206718a.gif)

**Comment by luzpaz** [comment]
Refinement: the left toolbar example is just showing us the bug when there are only 2 icons in the toolbar. If there are more that 2 you see the effect that happens in the right toolbar.

**Comment by nitramr** [comment]
Should be fixed in 9fe9da3ba30b9dae3589f56eba744ad464551466. I've added a flag which starts dragging only if mouse was pressed over a tab.

**Comment by luzpaz** [comment]
Confirmed fix on 9fe9da3ba30b9dae3589f56eba744ad464551466 
Nice job @nitramr 👍
