### ISSUE TITLE
emptied toolbar shrinks beyond the window manager buttons

### ISSUE THREAD

**Issue by luzpaz** [nitramr/indigoDock#37]
OSX 10.10.5 a39a9355895687cfdb31f678dce4851e5668c6bd Qt5.6 QtCreator4.0
reproduce:
1. pop the sidebar out 
2. start removing the contents of the sidebar till nothing remains in it
Result: See the toolbar window manager buttons become truncated and unavailable to use

See gif:
![toolbar-shrinks-past-window-manager-buttons](https://cloud.githubusercontent.com/assets/4140247/15382218/97bac8a6-1d4d-11e6-87e9-ea05bccf2cd5.gif)

**Comment by nitramr** [comment]
Fixed. It is not possible anymore to have empty docks.
