### ISSUE TITLE
transition from horizontal to vertical sidebar issues

### ISSUE THREAD

**Issue by luzpaz** [nitramr/indigoDock#38]
@nitramr you may be already aware of this but I'm posting anyway JIC
OSX 10.10.5 Qt5.6 QtCreator4.0 indigoDock revision 9fe9da3ba30b9dae3589f56eba744ad464551466

2 issues:
- [ ] Moving horizontal panel out of horizontal sidebar keeps it at an abnormally long width. Is there an intention to automatically shrink it down to manageable size once it's outside of the sideabar and in it's floating state ?
- [ ] ~~Moving horizontal panel out of horizontal sidebar in to floating state and then trying to snap it in to **empty** sidebar doesn't trigger snapping function~~ Duh, of course that won't work since there is no sidebar to snap it in to! Disregard this issue. 

See gif 
![moving-from-horizontal-to-vertical-sidebar-issue](https://cloud.githubusercontent.com/assets/4140247/15406994/74061a4c-1dce-11e6-8f7c-7d5abde5bd1d.gif)

**Comment by nitramr** [comment]
Floating panel size is fixed.

**Comment by luzpaz** [comment]
updated to bb4f02a668aa5177f41a399e7395753e053c1c8f
What I see:
Horizontal panels now are resized :)
Issues: 
The floating panel is not snapped directly under the mouse when you pull it out of the horizontal sidebar instead it's offset remotely. 
Also you can see issue #34 as well. 
![horizontal-panel-issues](https://cloud.githubusercontent.com/assets/4140247/15456542/3fcfa640-2039-11e6-837c-df72afc2ce36.gif)

**Comment by luzpaz** [comment]
I can't test on OSX anymore for the time being. AFAICT these issues are not present on Manjaro Linux 16.08 Qt5.7
There are other issues I found related to this but I will open them in a separate report. 
Thanks!
